### ISSUE TITLE
Assessment Review

### ISSUE THREAD

**Issue by rwarbelow** [bplantico/mod_0_skills#1]
**Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub**

- [x] Did you name and structure your directories and files correctly?
- [x] Did you make one initial commit?
- [x] Did you push your initial commit to Github?

**Part II: Top Down Design**

- [x] Did you break down larger processes into multiple smaller layers?
- [x] Did you add and commit your changes with a properly formatted commit message?
- [x] Did you push your changes to Github?

**Part III: Classes in a System** 

- [x] Did you structure and name your directories and files correctly?
- [ ] Did you correctly categorize attributes and methods for each class?

**Notes:** Check that your methods are things that the specific object can do. For example, a `Customer` object can't `ThankCustomer`. 

- [x] Did you correctly identify data types of attributes for each class?
- [x] Did you add and commit each set of changes separately with a properly formatted commit message?
- [x] Did you push your changes to Github?

**Assessment Results**
- [ ] Pass
- [x] Conditional pass: **Make changes to your methods for each class to ensure that the behaviors/actions are specific to that object**
- [ ] Fail with recommend for Mod 0 repeat
